#!/bin/sh
# p4recedit.sh
# Reconcile add all file types provided as arguments in command line

(set -o igncr) 2>/dev/null && set -o igncr; # correct line endings on Windows environments

cp -r ~/shadow_2/ ~/Desktop/shadow-no-units
rm -rf ~/Desktop/shadow-no-units/Assets/Resources/units
cp -r ~/shadow_2/Assets/Resources/units/scarab ~/Desktop/shadow-no-units/Assets/Resources/units
