#!/bin/sh
# p4recedit.sh
# Reconcile add all file types provided as arguments in command line

(set -o igncr) 2>/dev/null && set -o igncr; # correct line endings on Windows environments

sourcedir="/Users/Blake/shadow_2"
targetdir="/Users/Blake/Desktop/shadow-no-units"

cp -r $sourcedir $targetdir
rm -rf $targetdir/Assets/Resources/units/
mkdir $targetdir/Assets/Resources/units
cp -r $sourcedir/Assets/Resources/units/scarab $targetdir/Assets/Resources/units/scarab
